### PR TITLE
Update to API 1.1 - 4th revision

### PR DESCRIPTION
**Pull request by slackhead**
I'm getting an invalid command 'home,' error when I first load the script. I traced it down to line 1004:

input_data = input_data + ', tweet_mode="extended"'

I've removed it from this PR.

### CODE REVIEW

**Comment by slackhead** [comment]
Actually, I'm going to test this a while longer.

**Comment by slackhead** [comment]
Well it seems that the comma is the problem.

**Comment by DarkDefender** [comment]
Hmm, looking at the code again, it seems like there's a lot of unneeded `tweet_mode="extended"` stuff.
This is why I really didn't want to have  the code refactor and api pull in one. It is a lot easier to miss this stuff which is just what I did.

For example, you do not seem to do anything with the extra tweet_mode data you append to the input data.

It seems like you always use the extended mode regardless.
You also append it to the `options` list and do not seem to use it there either.

And I also do not know why you have extended tweet mode on line 848, you are only getting list of nicks there...

**Comment by slackhead** [comment]
Yes, I'm afraid the twitter dev docs on the API weren't much use for me - I did a lot by trial and error looking at the python twitter files and seeing what was being returned in the twitter buffer. I did use a bit of a blunderbuss and put it everywhere I saw a stream being opened.

Working with other people's code is never easy. The only example of the extended tweet mode in the python API is in archiver.py, which is of limited use.

**Comment by slackhead** [comment]
The first link on the dev page is 'Advertise' so I guess their priorities lie more in commercial use. Can't say I'm surprised really.

**Comment by DarkDefender** [comment]
@slackhead I've finally got time to take a look at the remaining stuff. I've removed userstreams and instead updated it to use the new prefered way (even if it's worse imho, I don't have much of a choice)

Would you be willing to see if I missed or broke something? The changes are on the master branch.

**Comment by slackhead** [comment]
Well I just had one so I guess it's ok. Perhaps doing a /upgrade a few days ago caused a problem. I'll continue to monitor.

**Comment by DarkDefender** [comment]
If you upgrade from weechat, then it will overwrite the script with an old version, yes.

Because the userstream api is on it's way out, there should now not be any stream delete messages anymore (because I'm not using streams)

**Pull request closed without merging**
