### PR TITLE
Make the length of tweet indexes adjustable

### PR DESCRIPTION
**Pull request by StarlitGhost**
This PR lets you adjust the length of tweet indexes via index_length, defaulting to the current length of 2.

If set to 3, indexes will run from aa0 to zz9
4 gives aaa0 to zzz9, and so on

This setting currently requires a script reload to take effect, you'd need to replace the generator in read_config to fix that.

### CODE REVIEW

**Comment by StarlitGhost** [comment]
I missed the setting conversion from str to int initially, I just force pushed a fix for that.

**Comment by StarlitGhost** [comment]
That should be easily possible, and yeah, I like that idea. I'll put something together when I get home in a few hours.

I think you'd need actual setting help text for this though, where currently none of the settings have any.

**Comment by DarkDefender** [comment]
Indeed, thank you very much for your work!

**Comment by DarkDefender** [comment]
I was a bit quick with this. This doesn't work with python3:
http://diveinto.org/python3/porting-code-to-python-3-with-2to3.html#next

**Pull request merged**
